apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-env
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  SYSTEM_URL	: {{ .Values.system_url | quote }}
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: {{ .Values.provider_name | quote }}
  PRODUCT_NAME: {{ .Values.product_name | quote }}
  APP_KIND: rest-with-apikey
  API_DESCRIPTION: {{- printf "%s %s" .Values.product_name "API"  -}}
  API_SPECIFICATION_URL: {{ .Values.spec_url | default "" | quote  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-config
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  headers.json: |-
    {
      {{ .Values.auth_header_name | quote }} : {{ .Values.auth_header_value | quote }}
    }
